### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by kingsea0-0** [easeflyer/gd_plugin#1]
环境为python 3.5 youdao_get和youdao_post两个文件运行都会有

Traceback (most recent call last):
  File "youdao_get.py", line 38, in <module>
    word = argv[1]
IndexError: list index out of range

**Comment by easeflyer** [comment]
感谢反馈。你可以再仔细看下 readme 或者可以敲入下面的命令尝试下：
./youdao_get.py  单词

如果你直接打：./youdao_get.py回车 则会报以上错误。
仔细看说明，一定能搞定，好运。
