### ISSUE TITLE
在windows上运行时报错

### ISSUE THREAD

**Issue by MeetWq** [easeflyer/gd_plugin#4]
好像是编码的问题，不知道怎么解决
![2019-12-02_143547](https://user-images.githubusercontent.com/33149974/69935860-150ca900-1511-11ea-82cc-8002f60b8d69.jpg)

**Comment by easeflyer** [comment]
你的 python 是什么版本？ 这个代码只支持 python3.5 以上版本。

**Comment by MeetWq** [comment]
python 是 3.7.3 的，我试了一下，直接运行脚本不会报错，但放到 goldendict 里面就会像上面那样

**Comment by easeflyer** [comment]
#5  和这个应该是同样的问题。请参考。

**Comment by bamanzi** [comment]
添加环境变量`PYTHONIOENCODING]=utf_8`即可解决，或者改成下面这样：

```python
if __name__ == "__main__":
    import os
    os.environ['PYTHONIOENCODING']='utf_8'
    ...
```

**Comment by bamanzi** [comment]
添加环境变量`PYTHONIOENCODING=utf-8`即可正常工作

**Comment by bamanzi** [comment]
我实际是写了一个bat脚本，然后在GoldenDict里面用配了`d:\youdao_get.bat %GDWORD%`

```
@echo off
set PYTHONIOENCODING=utf-8
cd D:\WinPython64-3.9\settings\
D:\WinPython64-3.9\python-3.9.5.amd64\python.exe youdao_get.py %1
```
