### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by SpeakSugar** [easeflyer/gd_plugin#5]
![image](https://user-images.githubusercontent.com/42370088/70418589-a8f4ec80-1a9e-11ea-93aa-d5f9232d8388.png)
hello.py里是youdao_get.py的代码 在shell命令行测试运行是成功的

**Comment by easeflyer** [comment]
推测，比较大的可能性是你本地 python 环境设置造成的问题。
比如linux环境下如果进行编译安装 python ？
编译安装 python 后，可能造成新的python 对于原有的包路径识别错误。

如果可能建议删除所有 python 环境，重新安装试试。
或者在 python3 前面加上完整路径尝试。

也可以 google/baidu  windows 环境 PYTHONPATH 相关的问题。

**Comment by SpeakSugar** [comment]
非常感谢！加上/usr/bin/python3解决了这个问题
但在命令行不加路径运行python3是可以的 这是为什么呢

**Comment by easeflyer** [comment]
这个你可以百度下，我印象可能是因为 shell 和 golddict 调用的 python 环境可能是不同的。
比如：1 用了不同的 python   2 两种方式读取了不同的 pythonpath 。

**Comment by SpeakSugar** [comment]
嗯嗯 非常感谢你的回复!
