### ISSUE TITLE
运行youdao_post.py 出现KeyError: 'translateResult' 我猜是url有问题

### ISSUE THREAD

**Issue by xtccc** [easeflyer/gd_plugin#6]
![图片](https://user-images.githubusercontent.com/37169212/74157559-7492dd80-4c53-11ea-8d70-0637474f227b.png)
我在出错的上边加了一个print：
![图片](https://user-images.githubusercontent.com/37169212/74157636-955b3300-4c53-11ea-8be6-f97fdf2b546e.png)
{"errorCode":50}看起来是网址url有问题？不太懂，不过yd_get.py没问题。

**Comment by easeflyer** [comment]
感谢反馈。确实yd_get.py 平时我自己也是用的比较多。推荐使用。
youdao_post.py 经过测试。确实适合长文。但是翻译质量，貌似还不如 yd_get.py
所以除非必须，还是建议用 yd_ge.py 按照段落翻译完全能应付。
